#!/usr/bin/env bash
source ./helpers

DOTFILES=(".vim" ".vimrc" ".ackrc" ".ctags" ".emacs")
DOT_FILES_DIR="dotfiles"

GOOGLE_DISK_ORGS="$HOME/Google Диск/orgs"
GOOGLE_DISK_POSTS="$HOME/Google Диск/posts"
SYMLINK_DIRS=("$GOOGLE_DISK_ORGS" "$GOOGLE_DISK_POSTS")

echo_ok "Creating symlinks"

for item in ${DOTFILES[*]}
do
  target="${HOME}/${DOT_FILES_DIR}/${item}"

  if [ -e $target ]
  then
      echo_warn "creating symlink: ${HOME}${item}"

      original_source="${HOME}/${item}"

      rm -rf $original_source
      ln -s $target $original_source
  fi
done

for i in ${!SYMLINK_DIRS[@]}
do
  item="${SYMLINK_DIRS[i]}"

  if [ -d "${item}" ]; then
    target_folder="$(basename "$item")"

    echo_warn "creating symlink: ~/$target_folder from $item"

    rm -rf "$HOME/$target_folder";
    ln -s "$GOOGLE_DISK_ORGS" "$HOME/$target_folder"
  fi
done

# mkdir ~/.config
