#!/usr/local/bin/bash

# Install home directory

# 1. Install symlinks

DOTFILES_DIR="$HOME/dotfiles"
source "$DOTFILES_DIR/helpers"

declare -a DOTFILES=(".vim" ".vimrc" ".ctags" ".emacs" ".zsh_plugins.txt")

echo_warn "Creating symlinks"

for item in ${DOTFILES[*]}
do
  target="$DOTFILES_DIR/$item"

  if [ -e $target ]
  then
      echo_warn "symlinked: $HOME/${item} -> $target"

      original_source="${HOME}/${item}"

      rm -rf $original_source
      ln -s $target $original_source
  fi
done

mkdir -p ~/.config/nvim/
touch    ~/.config/nvim/init.vim

# 2. Install vim package manager
test -f $HOME/.vim/autoload/plug.vim || { \
  echo_warn "Installing vim package manager";
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim;
}
