#!/bin/bash
DOTFILES_DIR="$HOME/dotfiles"
source "$DOTFILES_DIR/helpers"

echo_ok "Install starting. You may be asked for your password (for sudo)."

# homebrew
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
if hash brew &>/dev/null; then
	echo_ok "Homebrew already installed. Getting updates..."
	brew update
	brew doctor
else
	echo_warn "Installing homebrew..."
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

# brew install bash bash-completion bash-git-prompt

# version control
brew install git svn

# some regulars
brew install curl htop openssl

brew install ripgrep # grep replacement
brew install fd      # find replacement
brew install exa     # ls replacement
brew install fzf     #
brew install nvim --HEAD
brew install cask

# kubernetes
brew install kubectl
# kubernetes tail log viewer
brew install stern

brew cleanup

# cool developer fonts
brew tap homebrew/cask-fonts

FONTS=(
  font-fira-code
  font-roboto
  font-cascadia-code
  font-jetbrains-mono
)

brew cask install "${FONTS[@]}"

echo_ok "Fonts installed"

echo_ok "Complete"
