#!/bin/bash

DOTFILES_DIR="$HOME/dotfiles"
source "$DOTFILES_DIR/helpers"

# Symlinks for dotfiles
declare -a DOTFILES=(".vim" ".vimrc" ".ctags" ".emacs" ".zsh_plugins.txt")

echo_ok "Creating symlinks"

for item in ${DOTFILES[*]}
do
  target="$DOTFILES_DIR/$item"

  if [ -e $target ]
  then
      echo_warn "symlinked: $HOME/${item} -> $target"

      original_source="${HOME}/${item}"

      rm -rf $original_source
      ln -s $target $original_source
  fi
done

mkdir -p ~/.config/nvim/
touch    ~/.config/nvim/init.vim
