#!/usr/local/bin/bash

# Install all software required for modern development (kind of)

dotfiles_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source "$dotfiles_dir/helpers"

echo_ok "Install starting. You may be asked for your password (for sudo)."

# homebrew
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
if hash brew &>/dev/null; then
	echo_ok "Homebrew already installed. Getting updates..."
	brew update
	brew doctor
else
	echo_warn "Installing homebrew..."
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

# TODO: это откуда-куда?
git config --global pull.rebase true

brew install \
  bash bash-completion bash-git-prompt \
  git svn \
  curl htop openssl \
  ctags \
  ripgrep fd exa fzf jq \
  rbenv node \
  kubectl k9s stern \
  antibody \
  cask

brew install nvim --HEAD

# cool developer fonts
brew tap homebrew/cask-fonts

FONTS=(
  font-fira-code
  font-roboto
  font-cascadia-code
  font-jetbrains-mono
  font-iosevka
)

brew install --cask "${FONTS[@]}"

brew install --cask openinterminal

brew cleanup

echo_ok "Fonts installed"
echo_ok "OSX setup complete"
