#!/usr/local/bin/bash

# Install home directory

# 1. Install symlinks

dotfiles_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source "$dotfiles_dir/helpers"

dotfiles=(
  ".vim"
  ".vimrc"
  ".ctags"
  ".zshenv"
  ".zsh_plugins.txt"
)

echo_warn "Creating symlinks"

for item in ${dotfiles[*]}
do
  target="$dotfiles_dir/$item"

  if [ -e $target ]
  then
      echo_warn "Symlinking: $home/${item} -> $target"
      new_link="${HOME}/${item}"

      rm -rf $new_link
      ln -s $target $new_link || { echo_error "Link creation failed" && exit 1; }
      echo_ok "OK"
  fi
done

# 2. nvim init
#    TODO: add echoing >> here (for nvim init content)
mkdir -p ~/.config/nvim/
touch    ~/.config/nvim/init.vim

# 2. Install vim package manager
test -f $HOME/.vim/autoload/plug.vim || { \
  echo_warn "Installing vim package manager";
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim;
}
