#!/usr/local/bin/bash

# Install all software required for modern development (kind of)

DOTFILES_DIR="$HOME/dotfiles"
source "$DOTFILES_DIR/helpers"

echo_ok "Install starting. You may be asked for your password (for sudo)."

# homebrew
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
if hash brew &>/dev/null; then
	echo_ok "Homebrew already installed. Getting updates..."
	brew update
	brew doctor
else
	echo_warn "Installing homebrew..."
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

# brew install bash bash-completion bash-git-prompt

# version control
brew install git svn

git config --global pull.rebase true

# some regulars
brew install curl htop openssl

brew install ripgrep # grep replacement
brew install fd      # find replacement
brew install exa     # ls replacement
brew install fzf     #
brew install nvim --HEAD
brew install cask
brew install jq      # for json manipulations
brew install ctags
brew insrall rbenv
brew install k9s

# kubernetes
brew install kubectl
# kubernetes tail log viewer
brew install stern

# zsh package manager
# plugins list stored in .zsh_plugins.txt
brew install antibody

brew cleanup

# cool developer fonts
brew tap homebrew/cask-fonts

FONTS=(
  font-fira-code
  font-roboto
  font-cascadia-code
  font-jetbrains-mono
  font-iosevka
)

brew install --cask "${FONTS[@]}"

brew install --cask openinterminal

echo_ok "Fonts installed"
echo_ok "OSX setup complete"
