#!/usr/bin/env bash
DOTFILES_DIR="$HOME/dotfiles"
source "$DOTFILES_DIR/helpers"

# Symlinks sources
DOTFILES=(".vim" ".vimrc" ".ackrc" ".ctags" ".emacs")
GOOGLE_DISK_ORGS="$HOME/Google Диск/orgs"
GOOGLE_DISK_POSTS="$HOME/Google Диск/posts"
SYMLINK_DIRS=("$GOOGLE_DISK_ORGS" "$GOOGLE_DISK_POSTS")

echo_ok "Creating symlinks"

for item in ${DOTFILES[*]}
do
  target="$DOTFILES_DIR/$item"

  if [ -e $target ]
  then
      echo_warn "symlinked: $HOME/${item} -> $target"

      original_source="${HOME}/${item}"

      rm -rf $original_source
      ln -s $target $original_source
  fi
done

for i in ${!SYMLINK_DIRS[@]}
do
  item="${SYMLINK_DIRS[i]}"

  if [ -d "${item}" ]; then
    target_folder="$(basename "$item")"

    echo_warn "symlinked: $HOME/$target_folder -> $item"

    rm -rf "$HOME/$target_folder";
    ln -s "$GOOGLE_DISK_ORGS" "$HOME/$target_folder"
  fi
done

# mkdir ~/.config
