#!/usr/bin/env bash
DOTFILES_DIR="$HOME/dotfiles"
source "$DOTFILES_DIR/helpers"

# Symlinks for dotfiles
declare -a DOTFILES=(".vim"
          ".vimrc"
          ".ctags"
          ".emacs")

# Symlinks for folders
declare -a SYMLINK_DIRS=("$HOME/Google Диск/orgs"
              "$HOME/Google Диск/posts"
              "$HOME/Google Drive/orgs"
              "$HOME/Google Drive/posts")

echo_ok "Creating symlinks"

for item in ${DOTFILES[*]}
do
  target="$DOTFILES_DIR/$item"

  if [ -e $target ]
  then
      echo_warn "symlinked: $HOME/${item} -> $target"

      original_source="${HOME}/${item}"

      rm -rf $original_source
      ln -s $target $original_source
  fi
done

for i in ${!SYMLINK_DIRS[@]}
do
  item="${SYMLINK_DIRS[i]}"

  if [ -d "$item" ]; then
    target_folder="$(basename "$item")"

    echo_warn "symlinked: $HOME/$target_folder -> $item"

    rm -rf "$HOME/$target_folder";
    ln -s "$item" "$HOME/$target_folder"
  fi
done

# mkdir ~/.config
